language: python
python:
#  - "3.3"
#  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
# command to install dependencies
install:
  - make init
  - python setup.py install
# command to run tests
script:
  - make test