language: python
python:
#  - "3.3"
#  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install coverage
  - pip install codecov
  - make init
  - python setup.py install
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# command to run tests
script:
  - make test
after_success:
  - codecov -t 9405d6b0-fae0-4691-81f5-9b663648dca7
