language: python
python:
#  - "3.3"
#  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
# command to install dependencies
install:
  - pip install coverage
  - pip install codecov
  - make init
  - python setup.py install
# command to run tests
script:
  - make test
after_success:
  - codecov -t 9405d6b0-fae0-4691-81f5-9b663648dca7
  - bash <(curl -s https://codecov.io/bash)